# Based on list from https://pdimov.github.io/boostdep-report/boost-1.88.0/module-levels.html
# TODO: Generate this list automatically

BOOST_1_88_0_DEPS = {
    "level 0": {
        "callable_traits": [],
        "config": [],
        "crc": [],
        "headers": [],
        "hof": [],
        "lambda2": [],
        "leaf": [],
        "mp11": [],
        "pfr": [],
        "predef": [],
        "preprocessor": [],
        "qvm": [],
        "ratio": [],
    },
    "level 1": {
        "endian": ["boost.config"],
        "vmd": ["boost.preprocessor"],
        "winapi": ["boost.config", "boost.preprocessor"],
    },
    "level 2": {
        "container_hash": ["boost.config", "boost.describe", "boost.mp11"],
        "intrusive": ["boost.assert", "boost.config", "boost.move"],
        "throw_exception": ["boost.assert", "boost.config"],
        "timer": ["boost.config", "boost.io", "boost.predef"],
        "type_traits": ["boost.config", "boost.static_assert"],
        "variant2": ["boost.assert", "boost.config", "boost.mp11"],
    },
    "level 3": {
        "array": [
            "boost.assert",
            "boost.config",
            "boost.static_assert",
            "boost.throw_exception",
        ],
        "compat": ["boost.assert", "boost.config", "boost.throw_exception"],
        "concept_check": [
            "boost.config",
            "boost.preprocessor",
            "boost.static_assert",
            "type_traits",
        ],
        "container": [
            "boost.assert",
            "boost.config",
            "boost.intrusive",
            "boost.move",
        ],
        "core": [
            "boost.assert",
            "boost.config",
            "boost.static_assert",
            "boost.throw_exception",
        ],
        "hash2": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.describe",
            "boost.mp11",
        ],
        "uuid": [
            "boost.assert",
            "boost.config",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "system": [
            "boost.assert",
            "boost.config",
            "boost.throw_exception",
            "boost.variant2",
            "boost.winapi",
        ],
    },
    "level 4": {
        "align": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.static_assert",
        ],
        "bind": ["boost.config", "boost.core"],
        "charconv": ["boost.assert", "boost.config", "boost.core"],
        "circular_buffer": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.move",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "detail": [
            "boost.config",
            "boost.core",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.type_traits",
        ],
        "integer": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "interprocess": [
            "boost.assert",
            "boost.config",
            "boost.container",
            "boost.intrusive",
            "boost.move",
            "boost.winapi",
        ],
        "lexical_cast": [
            "boost.config",
            "boost.container",
            "boost.core",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "logic": ["boost.config", "boost.core"],
        "optional": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "scope": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.type_traits",
        ],
        "smart_ptr": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.throw_exception",
        ],
        "stacktrace": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.predef",
            "boost.winapi",
        ],
        "tuple": [
            "boost.config",
            "boost.core",
            "boost.static_assert",
            "boost.type_traits",
        ],
        "type_index": [
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.throw_exception",
        ],
        "unordered": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.mp11",
            "boost.predef",
            "boost.throw_exception",
        ],
        "utility": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.io",
            "boost.preprocessor",
            "boost.throw_exception",
            "boost.type_traits",
        ],
    },
    "level 5": {
        "any": [
            "boost.assert",
            "boost.config",
            "boost.throw_exception",
            "boost.type_index",
        ],
        "atomic": [
            "boost.align",
            "boost.assert",
            "boost.config",
            "boost.predef",
            "boost.preprocessor",
            "boost.type_traits",
            "boost.winapi",
        ],
        "conversion": [
            "boost.assert",
            "boost.config",
            "boost.smart_ptr",
            "boost.throw_exception",
        ],
        "dynamic_bitset": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.integer",
            "boost.move",
            "boost.static_assert",
            "boost.throw_exception",
        ],
        "exception": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.smart_ptr",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
        ],
        "format": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.optional",
            "boost.smart_ptr",
            "boost.throw_exception",
            "boost.utility",
        ],
        "function": [
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.throw_exception",
        ],
        "json": [
            "boost.align",
            "boost.assert",
            "boost.config",
            "boost.container",
            "boost.container_hash",
            "boost.core",
            "boost.describe",
            "boost.endian",
            "boost.mp11",
            "boost.static_assert",
            "boost.system",
            "boost.throw_exception",
        ],
        "mpl": [
            "boost.config",
            "boost.core",
            "boost.predef",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.type_traits",
            "boost.utility",
        ],
        "numeric_interval": [
            "boost.config",
            "boost.detail",
            "boost.logic",
        ],
        "pool": [
            "boost.assert",
            "boost.config",
            "boost.integer",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.winapi",
        ],
        "rational": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "safe_numerics": [
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.logic",
            "boost.mp11",
        ],
        "static_string": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.utility",
        ],
        "url": [
            "boost.align",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.mp11",
            "boost.optional",
            "boost.static_assert",
            "boost.system",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.variant2",
        ],
    },
    "level 6": {
        "chrono": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.move",
            "boost.mpl",
            "boost.predef",
            "boost.ratio",
            "boost.static_assert",
            "boost.system",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
            "boost.winapi",
        ],
        "context": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.mp11",
            "boost.pool",
            "boost.predef",
            "boost.smart_ptr",
        ],
        "function_types": [
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.mpl",
            "boost.preprocessor",
            "boost.type_traits",
        ],
        "metaparse": [
            "boost.config",
            "boost.mpl",
            "boost.predef",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.type_traits",
        ],
        "numeric_conversion": [
            "boost.config",
            "boost.conversion",
            "boost.core",
            "boost.mpl",
            "boost.preprocessor",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "outcome": [
            "boost.assert",
            "boost.config",
            "boost.exception",
            "boost.system",
            "boost.throw_exception",
        ],
        "random": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.dynamic_bitset",
            "boost.integer",
            "boost.io",
            "boost.static_assert",
            "boost.system",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "regex": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.integer",
            "boost.mpl",
            "boost.predef",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "scope_exit": [
            "boost.config",
            "boost.function",
            "boost.preprocessor",
            "boost.type_traits",
            "boost.typeof",
        ],
        "variant": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.detail",
            "boost.integer",
            "boost.mpl",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_index",
            "boost.type_traits",
            "boost.utility",
        ],
    },
    "level 7": {
        "coroutine": [
            "boost.assert",
            "boost.config",
            "boost.context",
            "boost.core",
            "boost.exception",
            "boost.move",
            "boost.system",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "coroutine2": [
            "boost.assert",
            "boost.config",
            "boost.context",
        ],
        "functional": [
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.function_types",
            "boost.mpl",
            "boost.preprocessor",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
        "local_function": [
            "boost.config",
            "boost.mpl",
            "boost.preprocessor",
            "boost.scope_exit",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
        "math": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.lexical_cast",
            "boost.predef",
            "boost.random",
            "boost.static_assert",
            "boost.throw_exception",
        ],
        "tti": [
            "boost.config",
            "boost.function_types",
            "boost.mpl",
            "boost.preprocessor",
            "boost.type_traits",
        ],
    },
    "level 8": {
        "fusion": [
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.function_types",
            "boost.functional",
            "boost.mpl",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.tuple",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
        "multiprecision": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.lexical_cast",
            "boost.math",
            "boost.predef",
            "boost.random",
            "boost.throw_exception",
        ],
    },
    "level 9": {
        "hana": [
            "boost.config",
            "boost.core",
            "boost.fusion",
            "boost.mpl",
            "boost.tuple",
        ],
        "iterator": [
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.fusion",
            "boost.mp11",
            "boost.mpl",
            "boost.optional",
            "boost.type_traits",
            "boost.utility",
        ],
        "parameter": [
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.fusion",
            "boost.mp11",
            "boost.mpl",
            "boost.optional",
            "boost.preprocessor",
            "boost.type_traits",
            "boost.utility",
        ],
    },
    "level 10": {
        "filesystem": [
            "boost.assert",
            "boost.atomic",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.detail",
            "boost.io",
            "boost.iterator",
            "boost.predef",
            "boost.scope",
            "boost.smart_ptr",
            "boost.system",
            "boost.type_traits",
            "boost.winapi",
        ],
        "heap": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.intrusive",
            "boost.iterator",
            "boost.parameter",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "lambda": [
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.iterator",
            "boost.mpl",
            "boost.preprocessor",
            "boost.tuple",
            "boost.type_traits",
            "boost.utility",
        ],
        "lockfree": [
            "boost.align",
            "boost.assert",
            "boost.atomic",
            "boost.config",
            "boost.core",
            "boost.parameter",
            "boost.predef",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "multi_array": [
            "boost.array",
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.functional",
            "boost.iterator",
            "boost.mpl",
            "boost.static_assert",
            "boost.type_traits",
        ],
        "multi_index": [
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.integer",
            "boost.iterator",
            "boost.move",
            "boost.mpl",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.utility",
        ],
        "parser": [
            "boost.assert",
            "boost.charconv",
            "boost.hana",
            "boost.type_index",
        ],
        "property_map": [
            "boost.any",
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_index",
            "boost.type_traits",
            "boost.utility",
        ],
        "range": [
            "boost.array",
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.conversion",
            "boost.core",
            "boost.detail",
            "boost.iterator",
            "boost.mpl",
            "boost.optional",
            "boost.preprocessor",
            "boost.regex",
            "boost.static_assert",
            "boost.tuple",
            "boost.type_traits",
            "boost.utility",
        ],
        "signals2": [
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.iterator",
            "boost.move",
            "boost.mpl",
            "boost.optional",
            "boost.parameter",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.variant",
        ],
        "tokenizer": [
            "boost.assert",
            "boost.config",
            "boost.iterator",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "yap": [
            "boost.hana",
            "boost.preprocessor",
            "boost.type_index",
        ],
    },
    "level 11": {
        "algorithm": [
            "boost.array",
            "boost.assert",
            "boost.bind",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.exception",
            "boost.function",
            "boost.iterator",
            "boost.mpl",
            "boost.range",
            "boost.regex",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.unordered",
        ],
        "bimap": [
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.iterator",
            "boost.lambda",
            "boost.mpl",
            "boost.multi_index",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "dll": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.filesystem",
            "boost.predef",
            "boost.smart_ptr",
            "boost.system",
            "boost.throw_exception",
            "boost.type_index",
            "boost.winapi",
        ],
        "flyweight": [
            "boost.assert",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.detail",
            "boost.interprocess",
            "boost.mpl",
            "boost.multi_index",
            "boost.parameter",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.unordered",
        ],
        "foreach": [
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.mpl",
            "boost.range",
            "boost.type_traits",
        ],
        "gil": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.filesystem",
            "boost.integer",
            "boost.iterator",
            "boost.mp11",
            "boost.preprocessor",
            "boost.type_traits",
            "boost.variant2",
        ],
        "iostreams": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.function",
            "boost.integer",
            "boost.iterator",
            "boost.mpl",
            "boost.numeric_conversion",
            "boost.preprocessor",
            "boost.random",
            "boost.range",
            "boost.regex",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "nowide": [
            "boost.config",
            "boost.filesystem",
        ],
        "program_options": [
            "boost.any",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.function",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tokenizer",
            "boost.type_traits",
        ],
        "proto": [
            "boost.config",
            "boost.core",
            "boost.fusion",
            "boost.mpl",
            "boost.preprocessor",
            "boost.range",
            "boost.static_assert",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
        "ptr_container": [
            "boost.array",
            "boost.assert",
            "boost.circular_buffer",
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.mpl",
            "boost.range",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.type_traits",
            "boost.unordered",
            "boost.utility",
        ],
        "sort": [
            "boost.config",
            "boost.core",
            "boost.range",
            "boost.static_assert",
            "boost.type_traits",
        ],
        "units": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.integer",
            "boost.io",
            "boost.lambda",
            "boost.math",
            "boost.mpl",
            "boost.preprocessor",
            "boost.static_assert",
            "boost.type_traits",
            "boost.typeof",
        ],
    },
    "level 12": {
        "assign": [
            "boost.array",
            "boost.config",
            "boost.core",
            "boost.move",
            "boost.preprocessor",
            "boost.ptr_container",
            "boost.range",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
        ],
        "date_time": [
            "boost.algorithm",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.io",
            "boost.lexical_cast",
            "boost.numeric_conversion",
            "boost.range",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tokenizer",
            "boost.type_traits",
            "boost.utility",
            "boost.winapi",
        ],
        "fiber": [
            "boost.algorithm",
            "boost.assert",
            "boost.config",
            "boost.context",
            "boost.core",
            "boost.filesystem",
            "boost.format",
            "boost.intrusive",
            "boost.predef",
            "boost.smart_ptr",
        ],
        "phoenix": [
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.fusion",
            "boost.mpl",
            "boost.predef",
            "boost.preprocessor",
            "boost.proto",
            "boost.range",
            "boost.smart_ptr",
            "boost.type_traits",
            "boost.utility",
        ],
        "test": [
            "boost.algorithm",
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.exception",
            "boost.function",
            "boost.io",
            "boost.iterator",
            "boost.mpl",
            "boost.numeric_conversion",
            "boost.optional",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.type_traits",
            "boost.utility",
        ],
        "xpressive": [
            "boost.assert",
            "boost.config",
            "boost.conversion",
            "boost.core",
            "boost.exception",
            "boost.fusion",
            "boost.integer",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.numeric_conversion",
            "boost.optional",
            "boost.preprocessor",
            "boost.proto",
            "boost.range",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
    },
    "level 13": {
        "asio": [
            "boost.align",
            "boost.assert",
            "boost.config",
            "boost.context",
            "boost.date_time",
            "boost.system",
            "boost.throw_exception",
        ],
        "icl": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container",
            "boost.core",
            "boost.date_time",
            "boost.detail",
            "boost.iterator",
            "boost.move",
            "boost.mpl",
            "boost.range",
            "boost.rational",
            "boost.static_assert",
            "boost.type_traits",
            "boost.utility",
        ],
        "thread": [
            "boost.assert",
            "boost.atomic",
            "boost.bind",
            "boost.chrono",
            "boost.concept_check",
            "boost.config",
            "boost.container",
            "boost.container_hash",
            "boost.core",
            "boost.date_time",
            "boost.exception",
            "boost.function",
            "boost.io",
            "boost.move",
            "boost.optional",
            "boost.predef",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.system",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.utility",
            "boost.winapi",
        ],
    },
    "level 14": {
        "beast": [
            "boost.asio",
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.container",
            "boost.container_hash",
            "boost.core",
            "boost.endian",
            "boost.intrusive",
            "boost.logic",
            "boost.mp11",
            "boost.optional",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.static_string",
            "boost.system",
            "boost.throw_exception",
            "boost.type_index",
            "boost.type_traits",
            "boost.winapi",
        ],
        "cobalt": [
            "boost.asio",
            "boost.callable_traits",
            "boost.circular_buffer",
            "boost.config",
            "boost.container",
            "boost.context",
            "boost.core",
            "boost.intrusive",
            "boost.mp11",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.system",
            "boost.throw_exception",
            "boost.variant2",
        ],
        "contract": [
            "boost.any",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.exception",
            "boost.function",
            "boost.function_types",
            "boost.mpl",
            "boost.optional",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.thread",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
        ],
        "locale": [
            "boost.assert",
            "boost.charconv",
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.predef",
            "boost.thread",
        ],
        "mysql": [
            "boost.asio",
            "boost.assert",
            "boost.charconv",
            "boost.compat",
            "boost.config",
            "boost.core",
            "boost.describe",
            "boost.endian",
            "boost.intrusive",
            "boost.mp11",
            "boost.optional",
            "boost.pfr",
            "boost.system",
            "boost.throw_exception",
            "boost.variant2",
        ],
        "process": [
            "boost.algorithm",
            "boost.asio",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.filesystem",
            "boost.fusion",
            "boost.io",
            "boost.iterator",
            "boost.move",
            "boost.optional",
            "boost.system",
            "boost.throw_exception",
            "boost.tokenizer",
            "boost.type_index",
            "boost.type_traits",
            "boost.utility",
            "boost.winapi",
        ],
        "redis": [
            "boost.asio",
            "boost.assert",
            "boost.core",
            "boost.mp11",
            "boost.system",
            "boost.throw_exception",
        ],
        "spirit": [
            "boost.array",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.endian",
            "boost.function",
            "boost.function_types",
            "boost.fusion",
            "boost.integer",
            "boost.io",
            "boost.iterator",
            "boost.move",
            "boost.mpl",
            "boost.optional",
            "boost.phoenix",
            "boost.pool",
            "boost.preprocessor",
            "boost.proto",
            "boost.range",
            "boost.regex",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.thread",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.typeof",
            "boost.unordered",
            "boost.utility",
            "boost.variant",
        ],
        "statechart": [
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.conversion",
            "boost.core",
            "boost.detail",
            "boost.function",
            "boost.mpl",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.thread",
            "boost.type_traits",
        ],
        "type_erasure": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.fusion",
            "boost.iterator",
            "boost.mp11",
            "boost.mpl",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.thread",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.typeof",
            "boost.vmd",
        ],
    },
    "level 15": {
        "convert": [
            "boost.config",
            "boost.core",
            "boost.function_types",
            "boost.lexical_cast",
            "boost.math",
            "boost.mpl",
            "boost.optional",
            "boost.parameter",
            "boost.range",
            "boost.spirit",
            "boost.type_traits",
        ],
        "mqtt5": [
            "boost.asio",
            "boost.assert",
            "boost.beast",
            "boost.container",
            "boost.core",
            "boost.endian",
            "boost.fusion",
            "boost.optional",
            "boost.random",
            "boost.range",
            "boost.smart_ptr",
            "boost.spirit",
            "boost.system",
            "boost.type_traits",
        ],
        "poly_collection": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.mp11",
            "boost.mpl",
            "boost.type_erasure",
            "boost.type_traits",
        ],
        "serialization": [
            "boost.array",
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.detail",
            "boost.function",
            "boost.integer",
            "boost.io",
            "boost.iterator",
            "boost.move",
            "boost.mp11",
            "boost.mpl",
            "boost.optional",
            "boost.predef",
            "boost.preprocessor",
            "boost.smart_ptr",
            "boost.spirit",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
            "boost.variant",
            "boost.variant2",
        ],
    },
    "level 16": {
        "geometry": [
            "boost.algorithm",
            "boost.any",
            "boost.array",
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container",
            "boost.core",
            "boost.function_types",
            "boost.fusion",
            "boost.integer",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.math",
            "boost.mpl",
            "boost.multiprecision",
            "boost.numeric_conversion",
            "boost.polygon",
            "boost.qvm",
            "boost.range",
            "boost.rational",
            "boost.serialization",
            "boost.static_assert",
            "boost.thread",
            "boost.throw_exception",
            "boost.tokenizer",
            "boost.tuple",
            "boost.type_traits",
            "boost.variant",
            "boost.variant2",
        ],
        "histogram": [
            "boost.config",
            "boost.core",
            "boost.math",
            "boost.mp11",
            "boost.serialization",
            "boost.throw_exception",
            "boost.variant2",
        ],
        "msm": [
            "boost.any",
            "boost.assert",
            "boost.bind",
            "boost.circular_buffer",
            "boost.config",
            "boost.core",
            "boost.function",
            "boost.fusion",
            "boost.mpl",
            "boost.parameter",
            "boost.phoenix",
            "boost.preprocessor",
            "boost.proto",
            "boost.serialization",
            "boost.tuple",
            "boost.type_index",
            "boost.type_traits",
            "boost.typeof",
        ],
        "property_tree": [
            "boost.any",
            "boost.assert",
            "boost.bind",
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.mpl",
            "boost.multi_index",
            "boost.optional",
            "boost.range",
            "boost.serialization",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
        "wave": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.filesystem",
            "boost.format",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.multi_index",
            "boost.optional",
            "boost.pool",
            "boost.preprocessor",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.spirit",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
        ],
    },
    "level 17": {
        "compute": [
            "boost.algorithm",
            "boost.array",
            "boost.assert",
            "boost.atomic",
            "boost.chrono",
            "boost.config",
            "boost.core",
            "boost.filesystem",
            "boost.function",
            "boost.function_types",
            "boost.fusion",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.optional",
            "boost.preprocessor",
            "boost.property_tree",
            "boost.proto",
            "boost.range",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.thread",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.typeof",
            "boost.utility",
            "boost.uuid",
        ],
        "graph": [
            "boost.algorithm",
            "boost.any",
            "boost.array",
            "boost.assert",
            "boost.bimap",
            "boost.bind",
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.conversion",
            "boost.core",
            "boost.detail",
            "boost.foreach",
            "boost.function",
            "boost.geometry",
            "boost.integer",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.math",
            "boost.move",
            "boost.mpl",
            "boost.multi_index",
            "boost.numeric_conversion",
            "boost.optional",
            "boost.parameter",
            "boost.preprocessor",
            "boost.property_map",
            "boost.property_tree",
            "boost.random",
            "boost.range",
            "boost.regex",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.spirit",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tti",
            "boost.tuple",
            "boost.type_traits",
            "boost.typeof",
            "boost.unordered",
            "boost.utility",
            "boost.xpressive",
        ],
        "log": [
            "boost.align",
            "boost.asio",
            "boost.assert",
            "boost.atomic",
            "boost.config",
            "boost.core",
            "boost.date_time",
            "boost.exception",
            "boost.filesystem",
            "boost.function_types",
            "boost.fusion",
            "boost.interprocess",
            "boost.intrusive",
            "boost.io",
            "boost.iterator",
            "boost.move",
            "boost.mpl",
            "boost.optional",
            "boost.parameter",
            "boost.phoenix",
            "boost.predef",
            "boost.preprocessor",
            "boost.property_tree",
            "boost.proto",
            "boost.random",
            "boost.range",
            "boost.regex",
            "boost.smart_ptr",
            "boost.spirit",
            "boost.system",
            "boost.thread",
            "boost.throw_exception",
            "boost.type_index",
            "boost.type_traits",
            "boost.utility",
            "boost.winapi",
            "boost.xpressive",
        ],
    },
    "level 18": {
        "numeric_ublas": [
            "boost.compute",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.iterator",
            "boost.mpl",
            "boost.numeric_interval",
            "boost.range",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.type_traits",
            "boost.typeof",
        ],
        "python": [
            "boost.align",
            "boost.bind",
            "boost.config",
            "boost.conversion",
            "boost.core",
            "boost.detail",
            "boost.foreach",
            "boost.function",
            "boost.graph",
            "boost.integer",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.numeric_conversion",
            "boost.preprocessor",
            "boost.property_map",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.tuple",
            "boost.type_traits",
            "boost.utility",
        ],
    },
    "level 19": {
        "accumulators": [
            "boost.array",
            "boost.assert",
            "boost.circular_buffer",
            "boost.concept_check",
            "boost.config",
            "boost.core",
            "boost.fusion",
            "boost.iterator",
            "boost.mpl",
            "boost.numeric_conversion",
            "boost.numeric_ublas",
            "boost.parameter",
            "boost.preprocessor",
            "boost.range",
            "boost.serialization",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.tuple",
            "boost.type_traits",
            "boost.typeof",
        ],
        "mpi": [
            "boost.assert",
            "boost.config",
            "boost.core",
            "boost.foreach",
            "boost.function",
            "boost.graph",
            "boost.integer",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpl",
            "boost.optional",
            "boost.python",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.utility",
        ],
        "parameter_python": [
            "boost.mpl",
            "boost.parameter",
            "boost.preprocessor",
            "boost.python",
        ],
    },
    "level 20": {
        "numeric_odeint": [
            "boost.assert",
            "boost.compute",
            "boost.config",
            "boost.core",
            "boost.fusion",
            "boost.iterator",
            "boost.math",
            "boost.mpi",
            "boost.mpl",
            "boost.multi_array",
            "boost.numeric_ublas",
            "boost.preprocessor",
            "boost.range",
            "boost.static_assert",
            "boost.throw_exception",
            "boost.type_traits",
            "boost.units",
            "boost.utility",
        ],
        "property_map_parallel": [
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.function",
            "boost.mpi",
            "boost.mpl",
            "boost.multi_index",
            "boost.optional",
            "boost.property_map",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.type_traits",
        ],
    },
    "level 21": {
        "graph_parallel": [
            "boost.algorithm",
            "boost.assert",
            "boost.concept_check",
            "boost.config",
            "boost.container_hash",
            "boost.core",
            "boost.detail",
            "boost.dynamic_bitset",
            "boost.filesystem",
            "boost.foreach",
            "boost.function",
            "boost.graph",
            "boost.iterator",
            "boost.lexical_cast",
            "boost.mpi",
            "boost.mpl",
            "boost.optional",
            "boost.property_map",
            "boost.property_map_parallel",
            "boost.random",
            "boost.serialization",
            "boost.smart_ptr",
            "boost.static_assert",
            "boost.tuple",
            "boost.type_traits",
            "boost.variant",
        ],
    },
}


def generate_boost_levels_markdown(boost_deps):
    """
    Generate markdown checklists for all boost dependency levels.

    Args:
        boost_deps (dict): Dictionary of boost dependency levels.

    Returns:
        str: Markdown formatted string with checklists for each level
    """
    markdown_content = ""

    for level_name, libraries in boost_deps.items():
        # Extract level number from level name (e.g., "level 1" -> "1")
        level_num = level_name.split()[-1]

        # Create the header with link
        markdown_content += f"## [Level {level_num}](https://pdimov.github.io/boostdep-report/boost-1.88.0/module-levels.html)\n\n"

        # Create checklist items for each library in this level
        for library_name in sorted(libraries.keys()):
            markdown_content += f"- [ ] {library_name}\n"

        markdown_content += "\n"

    return markdown_content


def generate_boost_level_markdown(boost_deps, level_name):
    """
    Generate markdown checklist for a specific boost dependency level.

    Args:
        boost_deps (dict): Dictionary of boost dependency levels.
        level_name (str): The level name (e.g., "level 3", "level 4")

    Returns:
        str: Markdown formatted string with checklist for the specified level
    """
    if level_name not in boost_deps:
        return f"Level '{level_name}' not found in boost_deps"

    libraries = boost_deps[level_name]
    level_num = level_name.split()[-1]

    markdown_content = f"## [Level {level_num}](https://pdimov.github.io/boostdep-report/boost-1.88.0/module-levels.html)\n\n"

    for library_name in sorted(libraries.keys()):
        markdown_content += f"- [ ] {library_name}\n"

    return markdown_content
